[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/virt.ld']

[target.riscv64gc-unknown-none-elf]
runner = "./ryos-qemu.sh -e "
# runner = """qemu-system-riscv64 \
#   -machine virt \
#   -cpu rv64 \
#   -smp 4 \
#   -m 128M \
#   -nographic \
#   -serial mon:stdio \
#   -bios none \
#   -drive if=none,format=raw,file=hdd.dsk,id=x0 \
#   -device virtio-blk-device,scsi=off,drive=x0 \
#   -kernel \
#   """

